name: Create Release Assets

on:
  release:
    types:
      - published

jobs:
  buildrpms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: fedora
            version: 40
            arch: aarch64
            dockernamespace: quay.io/fedora/fedora

    steps:
      - uses: actions/checkout@v3

      # Install qemu-user-static on the host for cross-platform support
      - name: Setup QEMU
        run: |
          sudo apt-get update && sudo apt-get install --yes binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      # Load environment variables
      - name: Get version
        run: |
          echo "VERSION=$(grep ^VERSION Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV

      - name: Get release
        run: |
          echo "RELEASE=$(grep ^RELEASE Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV

      - name: Specify A Target For make
        run: |
          echo "SPECIFICTARGET=github-release" >> $GITHUB_ENV

      - name: Environment variable for setting name of RPM when using EVDI from Github
        run: |
          echo "EVDISOURCE=.github_evdi" >> $GITHUB_ENV

      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV

      # Run the CI script inside the Docker container
      - name: Run CI script inside Docker container
        run: |
          docker run --rm \
            --platform linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ${{ matrix.dockernamespace }}:${{ matrix.version }}-aarch64 \
            bash -c "ci/${{ matrix.os }}.sh"

      # Rename files for clarity
      - name: Rename files
        run: |
          mv displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.src.rpm ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.src.rpm
          mv aarch64/displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.aarch64.rpm ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.aarch64.rpm

      - run: |
          chown $(id -u):$(id -g) -R .

      # Upload artifacts
      - name: Upload RPM
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}
          path: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm

      # Upload assets to release
      - name: Upload Assets To Release
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm"
          draft: false
          update_latest_release: true
          tags: true
          overwrite: true
